adding parameters for gw levels to data type mapping
usgs/aqts-capture-db pull request #33
Opened 2020-06-09 21:42 UTC by ssoper-usgs

Before making a pull request
----------------------------

- [ ] Make sure all tests run
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
If no JIRA ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the JIRA ticket
- [ ] Assign someone to review unless the change is trivial

2020-06-10 12:40 UTC, dsteinich requested changes

2020-06-10 12:40 UTC, dsteinich commented on liquibase/changeLogs/capture/data/dataTypeMapping/dataTypeMapping.tsv
> +72232	00024	tsDailyValueStatisticalTransform
This is an example of (me) not putting the blank line in and the compare showing a false positive change - line 169's real value didn't change, we just added new stuff on new lines after it. One more reason to always have the blank line (unless the load would choke on it).

2020-06-10 12:40 UTC, dsteinich commented on liquibase/changeLogs/capture/data/dataTypeMapping/dataTypeMapping.tsv
> +72019	null	discreteGroundWaterTransform
(IOW-453 has 99019 - do we need that here also?) 
ACTUALLY, based on yesterday's conversation everything is under "61055" "Water level, depth MP" "ft", and we should probably only have that.

2020-06-10 15:18 UTC, ssoper-usgs commented on liquibase/changeLogs/capture/data/dataTypeMapping/dataTypeMapping.tsv
> +72232	00024	tsDailyValueStatisticalTransform
I noticed this too, and was annoyed by it (the false positive).  +1 to keeping the blank lines moving forward.

2020-06-10 15:21 UTC, ssoper-usgs commented on liquibase/changeLogs/capture/data/dataTypeMapping/dataTypeMapping.tsv
> +72019	null	discreteGroundWaterTransform
I think 99019 doubles up on the value of another parm in the aq_to_nwis_parm table.  I was confused by that so I left it out on the first draft.

2020-06-10 21:36 UTC, ssoper-usgs commented on liquibase/changeLogs/capture/tables/discreteGroundWater/discreteGroundWater.sql
> +,parm_cd                                 text
Added this here, but can do a more formal changeset as well.  My thinking is that the capture.discrete_ground_water table is only on test, and not being used by anything yet, we might as well drop and replace.

2020-06-11 13:26 UTC, dsteinich approved these changes

2020-06-11 16:25 UTC, merged